cozy/cozy-settings

src/components/AccountView.jsx
src/components/PassphraseForm.jsx
src/locales/en.json
src/styles/fields.styl

The main goal is to avoid the feeling that the _save_ button's role is to save the whole form. To achieve that, we can:
* Switch locale and password position, to put password at the end and to not have a button in the middle of the form.
* Change the button label to make it more explicit
* Avoid to center the button, we may make its width to be 100%
* Use a secondary button instead as a primary one, as the submit action does not submit the whole form
* Switch position between button and _Forgot your passphrase_ link, to make the button more related to the old/new passphrases fieds
(with @kelukelu seal of approval)

# Improve UI/UX

---

src/index.ejs
src/main.jsx

Settings was still using the "old" way to include the cozy-bar and cozy-client-js, so things were a bit broken. This patch only fixes the bar, I'll submit a separate patch to use cozy-client-js if this one is ok.
@m4dz Aside from the changes included, is there anything in the webpack build process that I should change? Or something else I forgot?

[fix] Inject cozy bar with the stack

---

src/components/ProfileView.jsx
src/locales/en.json

This PR:
- fixes a typo in _e-mail_ translation in **en** source locale (we write _e-mail_, not _email_)
- avoid links in translation. To prevent errors or malicious links injections in locales, we only pass variables to the markdown content and interpolate them w/ polyglot

Translations fixes

---

manifest.webapp
src/actions/index.js
src/components/Input.jsx
src/components/InstallerView.jsx
src/containers/Installer.jsx
src/locales/en.json
src/main.jsx

Here is a second (see #36 ) implementation of the hidden application install/update screen.
This hidden screen is accessible with the following url : http://settings.cozy.local:8080/#/install
It is important that the settings application has the "settings" slug or else the stack will refuse any application install/update.
And it is also important that the cozy-stack is updated (at the moment, the docker image does not work)

 Application install/update screen implementation (SET-11) 

---

manifest.webapp
src/index.ejs
src/main.jsx

Adding Editor's name to the manifest so the stack can use it and make sure this data is shared so the cozy-bar can use it.
tl;dr: It displays the "Cozy" before the "Drive" in the Cozy-bar
Related PR: https://github.com/cozy/cozy-bar/pull/37

feat: Add Support for editor's name

---

src/services/Claudy.jsx
src/styles/services/claudy.css

@GoOz I just discover that `text-decoration` cannot be overwritten by the child elements, so I had to use some tricky code to handle that correctly (no text-decoration in my child element `<span>`) and overwrite styles from cozy-ui.

Add accounts count for cozy-collect claudy action :sparkles:

---

manifest.webapp

Specify the jobs permissions to explicitly ask for the `sendmail` worker. This evolution is required by this change in cozy-stack: https://github.com/cozy/cozy-stack/pull/950

Specify the jobs permissions

---

src/actions/index.js
src/components/StorageView.jsx
src/locales/en.json
src/styles/storage.styl
src/styles/view.styl

The offers link is compute from an URL in the context and the UUID of the instance. If one of these parameters are missing or `null` this part won't be displayed in the view.

Add offers button if offers link are available

---

.travis.yml
package.json
src/actions/email.js

The support mail sending was broken due to a wrong function signature.

Fix bug about support email sending

---

src/actions/services.js
src/config/claudyActions.yaml
src/reducers/claudy.js
src/services/Claudy.jsx

The gather action is the same as cozy-collect, so this PR rename the variables related to collect, but keeps also the cozy-collect action to ensure legacy. The cozy-collect action should be removed soon, once the Cozy-Bar will be updated.

Add gather action

---

src/index.ejs
src/services.ejs

Necessary to use the new cozy-bar navigation
and the home app detection

Get app slug from stack

---

src/services/ClaudyActionComponents/Support.jsx

In the claudy intent, the user can send an email to the support. When it's done, claudy comes back to the list of actions. But the componentWillReceiveProps method of Support was calling the goBack method of Claudy, when it makes React re-rendering and calling again the first method, etc. To fix that, we have added a condition to break the loop. It is a quick fix, a proper refactoring would need more work but could clean a lot more.

Do not freeze the browser on support email sent

---

src/components/IntentView.jsx

`this.setState()` was called in IntentViewer constructor. Making it crash since settings is no completely working with React.

Fix state usage in IntentViewer

---

package.json
yarn.lock

The goal is to be able to use AppLinker without introducing regressions due to last changes in cozy-ui variable names

Downgrade dependency cozy-ui to 19.29.0

---

src/actions/twoFactor.js
src/reducers/fields.js
src/reducers/fields.spec.js

The auth_mode field should react to two fa actions, *as well* as normal value actions. Checkbox would not show its state otherwise.

fix: Also responds to normal value reducer

---

src/styles/fields.styl
src/styles/loading.styl
src/styles/spinner-blue.svg
src/styles/spinner.styl
src/styles/table.styl
src/styles/view.styl

Cozy-ui has removed $icon-spinner-blue but settings is still
using it. Copy back the $icon-spinner-blue placeholder in settings.

fix: Styles need $icon-spinner-blue placeholder

---

src/actions/index.js
src/actions/services.js
src/containers/Profile.jsx
src/services/Claudy.jsx
src/targets/browser/index.jsx

Those console calls seem to be here for a long time and are causing warnings in the linter.

chore: Remove console eslint warnings

---

src/targets/browser/index.jsx

Passing a prop was making any query to never update its fetchstatus.
Related to https://github.com/cozy/cozy-client/issues/439

Remove CozyProvider store prop

---

package.json
yarn.lock

The cozy-bar now bundles its own cozy-ui, which should fix the stylesheets conflicts we had between the cozy-bar's cozy-ui and app's cozy-ui.
See https://github.com/cozy/cozy-bar/pull/608 for more infos.

chore(deps): Update cozy-bar to v7.6.0

---

jest.config.js
package.json
src/actions/passphrase.js
src/components/2FA/index.jsx
src/containers/Profile.jsx
test/components/__snapshots__/sidebar.spec.js.snap
yarn.lock

When updating the instance's passphrase, we need to update bitwarden's keys.
At the moment, only the case without 2FA is working because there is a loop in the 2FA case (calls to bitwarden APIs asking for a 2FA code). This is going to be fixed on the stack side. This PR is in WIP state, waiting for this stack fix.
See https://github.com/cozy/cozy-stack/pull/2089

feat: Update bitwarden hash and keys when updating passphrase

---

src/locales/en.json

Adding the `manifest` field in the translations so that we can change the app's name depending on the locale, through transifex.

feat: Make app name translatable

---

src/components/DeleteAccount/FormModal.jsx

The (arbitrary) limit for the message when deleting a cozy was too small for some feedback messages, and the user was not aware that there was a limit on the message size. This PR fixes both issues.

Mail limit

---

src/styles/passphrase.styl

fix(PassphraseForm): Make password advice align properly with text

---

package.json
test/__snapshots__/app.spec.js.snap
yarn.lock

The password strength rendering was buggy:
* It was "jumping" between strength levels while typing the password
* The strength changed when interacting with a totally not related input
The bug was fixed in cozy-ui v29.1.1, see
https://github.com/cozy/cozy-ui/releases/tag/v29.1.1.

fix: Password strength rendering

---

package.json
src/reducers/emailStatus.js
src/reducers/emailStatus.spec.js

Settings offers a contact form as an inter-app feature, which is notably used in the cozy bar. The form works, but there is no UI feedback when the email is sent, the spinners keep turning.
This was caused by a missing case in the reducer, fixed in this PR.

Fix email intent

---

package.json
yarn.lock

Since Chrome 82 or 83, they changed the default alignment for buttons.
so we need to force it now.
See the fix in UI : https://github.com/cozy/cozy-ui/pull/1399

fix: Upgrade Cozy-UI to fix visual regressions with Chrome

---

manifest.webapp
package.json

Bump to 1.15.0 since we're releasing an 1.14.0 version

chore: Bump to 1.15.0

---

src/components/export/ExportDownload.jsx

A regression was introduced by a previous refactoring
(https://github.com/cozy/cozy-settings/commit/84676c2d3ad5df1e7bb76e50b39eadbc5ebb4734)
The componentDidMount function does not take props as an argument, but
from this.

fix: Fix the export page

---

package.json
src/components/2FA/Activate2FA.jsx
src/components/DeleteAccount/FormModal.spec.jsx
src/targets/browser/index.jsx
src/targets/intents/index.jsx
yarn.lock

Upgrade to use MUI V4
- Upgrade dependencies
- @material-ui/core 3.9.4 -> 4.11.3
- cozy-ui 44.2.0 -> 45.1.0
- Added @testing library react for testing

feat: Upgrade cozy ui with MUI V4

---

src/components/DeleteAccount/FormModal.jsx
src/components/DeleteAccount/FormModal.spec.jsx
src/components/export/ExportSection.jsx
src/targets/browser/index.jsx
src/targets/intents/index.jsx

- feat: Add flag for enable "cozy move"
- fix: Add client param to sendDeleteAccountRequest 
There was an error : "client.collection is not a function" when the user wants to delete their account.
because the client was missing in params of sendDeleteAccountRequest

Add Move flag + fix delete account request

---

src/locales/en.json

additional take only one n in english.

Fix a typo in the Two steps authentication dialog

---

src/lib/passwordHelper.js

The password strength indicator uses the classes of the characters in
the password, but some characters weren't classified correctly:
- `É` is an uppercase letter
- `$` is a symbol

fix: Fix password strength computation

---

config/webpack.config.piwik.js

Our matomo instance will now be available at matomo.cozycloud.cc
instead of piwik.cozycloud.cc.

chore: Change matomo URL

---

src/components/DevicesModaleConfigureView.spec.jsx
src/locales/en.json
src/locales/fr.json

Since the device configuration is only saved after the validation
button has been clicked, it seemed more appropriate to use a term like
`Validate` rather than the simple `OK` which could lead the user to
think it's not mandatory to click it.

fix: Change device configuration validation CTA

---

src/components/CozyTreeView.jsx
src/components/__snapshots__/DevicesModaleConfigureView.spec.jsx.snap

Safari won't display the `expand` and `collapse` icons of a `TreeView`
if their size is not specified.
We simply move the size definition from the container class to icon
props.

fix: Force TreeView icons size

---

package.json
src/components/DevicesView.jsx
yarn.lock

The partial synchronization configuration should only be available for
Desktop clients with a minimum version of 3.32.0-beta.2 as earlier
versions require a flag to be activated to handle partial
synchronization or don't handle it at all.
We still require the flag to be activated for the button to be shown
though.
We add a new dependency to `semver` to help us compare the Desktop 
clients' version with our minimum version.

feat: Configure Desktop from version 3.32.0-beta.2

---

src/components/DevicesView.jsx

The actual Desktop version activating partial synchronization support
in the core synchronization process without a flag is v3.32.0-beta.3
and not v3.32.0-beta.2 as stated in the previous commit.
This commit simply fixes this mistake.

fix: Configure Desktop from version 3.32.0-beta.3

---

package.json

date-fns is not used in the app (it is still present in yarn.lock because used in dependencies)
close #261

fix(deps): remove unused date-fns

---

src/components/LanguageSection.jsx
src/locales/de.json
src/locales/de_DE.json
src/locales/en.json
src/locales/es.json
src/locales/fr.json
src/locales/ja.json
src/locales/nl_NL.json
yarn.lock

On the Profile page, in the Language section, the link "Here's how to help us" pointed to a page that displays an error message "Oops! That page doesn't exist or is private."

fix : Remove a broken link 🔗

---

.travis.yml

Notifications of repository publications were sent in an old channel that is no longer used

fix: Update Mattermost channel

---

manifest.webapp
src/containers/Permission.jsx
src/containers/Permissions.jsx
src/containers/Permissions.spec.jsx
src/containers/__snapshots__/Permissions.spec.jsx.snap
src/doctypes/index.js

First commit : This fix should have been in github.com/https://github.com/cozy/cozy-settings/pull/414
Second commit : Add konnectors to permissions page and alphabetical sort on applications/konnectors name

Add konnectors to permissions page

---

jest.config.js
package.json
src/targets/browser/index.jsx
src/targets/intents/index.jsx
test/jestLib/custom-test-env.js
yarn.lock

Fixing previous by using root and root.render instead of { render }
However cozy-bar is still shouting React 18 version issue.

feat(react): upgrade to react-18

---

src/containers/Permission.jsx
src/containers/Permission.spec.jsx
src/containers/PermissionsApplication.jsx
src/containers/PermissionsApplication.spec.jsx
src/containers/__snapshots__/Permission.spec.jsx.snap
src/containers/__snapshots__/PermissionsApplication.spec.jsx.snap
src/containers/helpers/permissionsHelper.js
src/containers/helpers/permissionsHelper.spec.js
src/lib/withAllLocales.js
src/lib/withAllLocales.spec.js
src/lib/withLocales.js
src/locales/en.json
src/locales/fr.json

1: On an app / konnector permissions list, display 'Read' / 'Write' or both instead of verbs
2: Bug fixed: If a permission of a konnector was clicked, 'Failed request' was displayed instead of the verbs
3: When a permission of an app or a konnector is clicked, verbs replaced by details ( 'Read' / 'Write' / both)

 feat(Permissions): Display permissions type details instead of verbs

---

src/containers/Permissions.jsx
src/containers/Permissions.spec.jsx

When the user uses his Cozy, he does not see the home, settings or the store as applications but as the Cozy platform. Technically they are definitely apps but they are not seen as such functionally. That's why they should not be displayed

fix: Remove Home, Store and Settings from the list of apps

---

src/components/App.jsx
src/components/Permissions/AppList.jsx
src/components/Permissions/AppList.spec.jsx
src/components/Permissions/DataList.jsx
src/components/Permissions/DataList.spec.jsx
src/components/Permissions/PermissionsTab.jsx
src/components/Permissions/PermissionsTab.spec.jsx
src/components/Permissions/__snapshots__/AppList.spec.jsx.snap
src/components/Permissions/__snapshots__/DataList.spec.jsx.snap
src/components/Permissions/__snapshots__/PermissionsTab.spec.jsx.snap
src/components/Sidebar.jsx
src/components/Sidebar.spec.jsx
src/constants/routes.js
src/containers/Permission.jsx
src/containers/Permission.spec.jsx
src/containers/PermissionsApplication.jsx
src/containers/__snapshots__/Permission.spec.jsx.snap
src/lib/withAllLocales.spec.js
src/locales/en.json
src/locales/fr.json
src/test/AppLike.jsx
test/__snapshots__/app.spec.js.snap

The list of applications is now on the path '#/permissions/slug',
The data page is on the path '#/permissions/data'

feat: Add tab to display DataList

---

.eslintrc.json
jest.config.js
package.json
tsconfig.json

Nothing is required after pulling this commit.
You can continue coding in js/jsx or start using TypeScript.
Be warned that TypeScript is in strict mode,
AND even stricter with ESLint.
ESlint errors will fail the CI. TS errors though will not fail the CI.
I would still advise you to not let any TS error subsist,
else TS doesn't make really sense.

feat: Enable TypeScript support on the application

---

package.json
src/components/App.jsx
src/components/CozyTreeView.jsx
src/components/PageTitle.jsx
src/components/Sidebar.tsx
src/components/menu/MenuList.tsx
src/components/menu/menu.styl
src/hooks/useOffersLink.ts
src/lib/makeDiskInfos.spec.ts
src/lib/makeDiskInfos.ts
src/locales/en.json
src/locales/fr.json
yarn.lock

This handles many small UI fixes needed after staging review. See the [ticket](https://trello.com/c/J1yWZ7pS/573-%E2%9A%99%EF%B8%8F-set-menu-en-premi%C3%A8re-page-dans-lapplication-settings-4j) for more informations.
This is in the broad context of biometrics features to be added to the Flagship App. Perfecting the UI on the web is still part of what we have to do.
CSS adjusting, new hook for getting manager link, updated hook to round disk usage percentage, new icons, nothing big.
No tests were added, it didn't seem useful as most of the features are in Typescript. Existing tests were updated though.
Might be still useful to add tests down the road to all new hooks even if they're fully typed.

fix: Improve new menu after staging

---

src/components/Permissions/PermissionsTab.jsx
src/components/Permissions/__snapshots__/PermissionsTab.spec.jsx.snap

- delete divider
- shorten the tab
from this :
to that :

fix: Update Permission Tab

---

src/components/App.jsx
src/styles/index.styl

Related to https://trello.com/c/FhQCY4DE/590-scroll-inutile-dans-le-menu-de-settings
When on the Menu page on mobile, there is an unwanted and apparently useless Y scrolling ability. It makes the UI look semi-broken.
Overwriting the `:after` pseudo-element in `Layout` when on a small screen because this page is a special case and doesn't have anything to show on the bottom of the page (like a bottom sidebar which we do not have anymore on `cozy-settings`). So we just remove that pseudo-element which was creating unwanted scrolling.
Manual testing in the browser
At this point, I didn't think updating `cozy-ui` was necessary because it is a special app scenario

fix: Remove vertical scrolling on mobile menu

---

src/components/Sidebar.tsx
src/hooks/useOffersLink.ts
src/locales/en.json

It is not needed as the instance context already knows if the feature
is enabled or not.
It probably was a legacy check for testing purpose.
Also fixed a typing
Also updated the button locale in EN

fix: Remove flag for Subscription link

---

package.json
yarn.lock

`cozy-client` as been upgraded to to `33.0.8` to spread attributes in the response data also with get requests. See https://github.com/cozy/cozy-client/pull/1246

feat: Update cozy client

---

src/targets/browser/index.ejs

This is the recommended way in order to get all the new added attributes without editing the ejs.

fix: Use only one way to inject data

---

src/targets/browser/index.jsx

Since c7bf132a1dc71e042e1b1d4612893280839738a1
we changed the way to store the data from the
cozy-stack.
Let's read the data from the right path.

fix: Use correct data to init the cozy-bar

---

manifest.webapp

`@build` is not a supported syntax by github,
the link was broken.
And since we don't push inside the build branch
anymore, let's only use the path to the repository

fix: Change source url

---

src/actions/email.spec.js
src/actions/passphrase.js
src/components/DeleteAccount/FormModal.spec.jsx
src/components/DeleteAccount/helpers.spec.js
src/components/ProfileView.spec.jsx
src/lib/client.js
src/reducers/index.js
src/store.jsx
src/targets/browser/index.jsx
src/targets/intents/index.jsx

Let's update this old code to follow new convention. Also fix a warning 'CozyClient is already logged'

refactor: No need to use CozyClient.fromDOM

---

package.json
src/hooks/useOffersLink.ts
yarn.lock

When refactored query() to fetchQueryAndGetFromState() we lose this option, we fixed the real issue in cozy-client https://github.com/cozy/cozy-client/commit/a840bf46e2d6b5f28572e3f1d9f9558765d8e085 but let's be explict, this is better

fix: use singleDocData

---

src/components/Permissions/AppPermissions/AppPermissions.jsx
src/components/Permissions/AppPermissions/AppPermissions.spec.jsx
src/components/Permissions/AppPermissions/__snapshots__/AppPermissions.spec.jsx.snap
src/components/Permissions/DataList/DataList.jsx
src/components/Permissions/DataList/DataList.spec.jsx
src/components/Permissions/DataPermissions/DataPermissions.jsx
src/components/Permissions/DataPermissions/__snapshots__/DataPermissions.spec.jsx.snap
src/locales/en.json

- Translation was not showing in DataList and DataPermissions due to a change in cozy-client (removed '.Permissions' to access a doctype)
- Change translations of section titles in AppPermissions
- Add english translation for "number of applications" in DataList
- Rename "PermissionsApplications" to "AppPermissions" to match file name

fix: Fixed several issues

---

src/components/Permissions/AppPermissions/AppPermissions.jsx
src/components/Permissions/LatestOutgoingDataHistory.jsx
src/components/Permissions/helpers/permissionsHelper.js
src/locales/en.json

- Before, all remote requests elements were shown in 'Last outgoing data history' section, now only items created by the current app are shown
- Before "Monthly Stats" was the name of all remote requests elements, now it is the name of the doctype
- Renamed this section's file name

feat: Filter 'last outgoing data history' section elements

---

src/components/pages/LockScreen.tsx
src/lib/logger.js

Biometry settings on mobile app
The biometry input wasn't triggering any bar overlay change, they stayed white
Adding (for Android only as iOS doesn't have the issues) setFlagshipUI calls on open/close of the biometry prompt
Manual only
Code is verbose as is usual with setFlagshipUi but this topic can't be tackled in a bug fix

fix: Add overlay to UI when using biometry

---

src/locales/en.json

The variable wasn't put in the english json file. It will now work as
in the French version.
See: https://github.com/cozy/cozy-settings/blob/7c21722945f367722b9512e5a4883f874107b9fb/src/locales/fr.json#L92

fix: add `percent` variable in EN locale

---

src/components/pages/LockScreen.tsx

This is a new feature, making pinCode behaves like biometry.
When they are activated, autoLock gets automatically activated too.

feat: pinCode activation also sets autoLock to true

---

src/actions/passphrase.js
src/containers/Passphrase.jsx

The getDomain() gives a string that is not valid for URL construction.
We decide to leverage the client HoC and inject the correct uri
in the aforementioned functions

fix: provide instance URL to passphrase function

---

src/components/Permissions/PermissionsTab.jsx
src/components/Permissions/PermissionsTab.spec.jsx
src/components/Permissions/__snapshots__/PermissionsTab.spec.jsx.snap
src/locales/en.json
src/locales/fr.json

- Desktop: h3 for "Permissions" title
- Mobile: Header in cozy bar
- Mobile: Back arrow in cozy bar

feat: Update DataList and AppList headers

---

src/components/menu/MenuItemAnchor.tsx
src/components/menu/MenuItemButton.tsx
src/components/menu/MenuItemNavLink.tsx
src/components/menu/MenuItemSwitch.tsx
src/components/pages/LockScreen.tsx

Also, disable the ellipsis on all buttons as they are intended for small screens.

fix: reorder flagship specific menu

---

src/components/Permissions/AppPermissions/AppPermissions.jsx
src/components/Permissions/AppPermissions/__snapshots__/AppPermissions.spec.jsx.snap

On `AppPermissions.jsx` we want a specific gap between title's actions buttons
Cozy's class utilities does not give any class for handling Flexbox's gap, so instead this commit uses a Grid component with `spacing` instruction

fix: Use grid instead of flexbox for AppPermissions title actions

---

src/components/PageTitle.jsx
src/components/Permissions/AppPermissions/AppPermissions.jsx
src/components/Permissions/DataPermissions/DataPermissions.jsx

With previous implémentation, clicking on the cozy-bar's back button on mobile view would navigate from `#/permissions/slug/:slug` to `#/menu` instead of `#/permissions/slug`
This commit is an attempt to fix the back button behaviour on `AppPermissions.jsx` until we find a more generic way

fix: Correctly handle navigation when clicking on permission back button

---

src/components/Permissions/AppPermissions/AppPermissions.jsx
src/components/Permissions/AppPermissions/AppPermissions.spec.jsx
src/components/Permissions/PermissionDetails/PermissionDetails.tsx
src/components/Permissions/PermissionDetails/PermissionDetailsModal.jsx
src/components/Permissions/PermissionDetails/PermissionDetailsModalContent.jsx

We displayed the technical name (slug) to the end user. We fixed it, by display the right thing to the user
Before: 
After:

fix: Use displayName instead of Slug

---

src/components/DefaultRedirectionSection.jsx

Use getAppDisplayName for default redirection app list name
And we sort just after because :
- we are not sure that the array was sorted
- even if it was, it may not be anymore with getAppDisplayName

fix: Use getAppDisplayName for default redirection app list name

---

src/components/Permissions/DataList/DataList.jsx
src/components/Permissions/PermissionsTab.jsx
src/components/Permissions/__snapshots__/PermissionsTab.spec.jsx.snap

Regression following centring of the empty state in the device view (cf: [commit](https://github.com/cozy/cozy-settings/commit/013e221e794504d3fa0645f616242749d9075ed9)). I've standardised the use of the `Page` component, but adaptation for `DataList` component was incorrect. I took advantage of this to centralise margin management at parent level

fix: AppList margin regression

---

src/components/LanguageSection.jsx
src/hooks/useSetLang.spec.tsx
src/hooks/useSetLang.ts

This will allow the flagship app
to update its language on real time
when it has been successfully updated
from the cozy-settings app
using cozy-intent when current language is changing
listening to UI props to be in sync

feat: send a react-native message on setLang

---

src/components/Devices/DevicesView.jsx
src/components/Devices/DevicesView.spec.jsx

Pending OAuth clients are clients that are not fully configured yet
(e.g. permissions haven't been accepted yet).
We should hide these clients as they're not really relevant to the
user and we could even get into annoying situations like the user
revoking the client their trying to connect.
These clients are deleted after 1 hour if they're still pending.

feat: Hide pending OAuth clients in DevicesView

---

src/locales/en.json

The PIN code dialog was not translated in english and was displayed with dummy strings. This PR fixes that by adding correct translations.
Here are the french vs english comparison to help reviewing translations in their own context.
First step:
Second step:

fix: Set english translations for PIN code dialog

---

package.json
yarn.lock

This update gets a fix from cozy-client to handle when the user has password_defined set to undefined
```
- Update cozy-client from 40.2.1 to 40.4.1
```

feat: Update cozy-client from 40.2.1 to 40.4.1

---

src/components/App.jsx
src/components/SettingsRealTimeQueries.jsx
src/components/SettingsRealTimeQueries.spec.jsx

The document sent by cozy-stack in real time is the CouchDB document. Unlike a call to the JSON Api, the document does not contain the attribute field. When a change was made, it generated a conflict error. I modified the RealTimeQueries so that I could modify the real-time object before integrating it into the cozy-client. This makes it possible to have the same version everywhere and avoid conflicts.
See also: https://github.com/cozy/cozy-client/issues/1412

fix: Realtime conflict into Profile page

---

src/components/export/ExportDownload.jsx

When the export dialog may propose to download the Cozy's data in multiple parts
When doing so, a list of each available part is displayed
But when no part is available (i.e. only a single archive is proposed) then only the download button should be displayed
With previous implementation, the character `0` would have been displayed instead of an empty list

fix: Correctly display export dialog when there is no cursor

---

src/components/App.jsx

```
* Remove prefix into bar app name
```

[VO-489] fix: Remove prefix into bar app name

---

src/components/PassphraseForm.jsx

In 3cfb9fcbda7f5f3292c88b1fc09d0b16b221e7da we migrated `react/deprecated/Button` to `react/Buttons`
Those 2 components have a different default behaviour
`react/deprecated/Button` would produce a button with type `submit` by default
`react/Buttons` would produce a button with type `button` by default
In `PassphraseForm` we expect the button to act as a `submit` as we are inside of a `<form>` element
As the new default type is `button`, the user cannot change their password anymore as the generated `button` would do nothing (there is no `onClick` instruction on it)
To fix this we want to explicitly ask for a `submit` type, so we rollback to the previous behaviour
Related commit: 3cfb9fcbda7f5f3292c88b1fc09d0b16b221e7da
```
*
* Fix a bug that prevented to change password from the …
```

fix: Change PassphraseForm's buttons types for `submit`

---

.travis.yml
release.config.js

The package `cozy-app-publish` is now a dev dependencie of this projet. These is to avoid commiting modification of package.json without the yarn-lock each time after installation into Travis script

chore: Remove useless installation in travis

---

src/targets/browser/index.ejs
src/targets/intents/index.ejs

Our custom theme CSS was not taken into account because cozy-ui CSS was inserted after.
```
* Custom theme colors were not taken into account
```

fix: Move custom theme CSS at end of <head>

---

package.json
src/components/Devices/__snapshots__/DevicesModaleConfigureView.spec.jsx.snap
yarn.lock

To better support dark mode (flagship app and dark mode button in cozy-settings).
```
*
*
* Update cozy-ui to 110.1.0 (better dark mode support)
```

feat: Update cozy-ui to 110.1.0

---

src/actions/passphrase.js

Previously, we attempted to hash the new password using the same encryption parameters as the initial password. In cases where the initial password was hashed with low kdf iterations, this led to server rejections. Thus commit fore a higher kdf iterations for new passwords to ensure compatibility with server requirements
```
* Enforce stronger encryption for new password hashing
```

[VO-780] fix: Enforce stronger encryption for new password hashing

---

src/components/Profile/Import.jsx
src/components/export/MoveButton.jsx
src/locales/en.json
src/locales/fr.json

```
* Improve wordings on data section
*
*
```

feat: Improve wordings on data section

---

package.json
yarn.lock

Upgrade cozy-ui dependency from previous version to 124.2.0 This includes updated components and styling improvements.

chore: Update cozy-ui to version 124.2.0
