package.json
src/components/AccountView.jsx
src/components/InputEmail.jsx
src/components/InputText.jsx
src/components/PassphraseForm.jsx
src/components/SelectBox.jsx
src/containers/AccountManagement.jsx
src/lib/emailHelper.js
src/locales/en.json
src/store/SettingsStore.js
src/styles/inputEmail.styl
src/styles/inputText.styl
src/styles/passphraseForm.styl
src/styles/selectBox.styl
yarn.lock

To setup properly the environment you should:
1. launch a standalone CouchDB instance with Docker
`docker run -d \
--name cozy-stack-couch \
-p 5984:5984 \
-v $HOME/.cozy-stack-couch:/opt/couchdb/data \
klaemo/couchdb:2.0.0`
2. serve with cozy-stack (in the app's directory)
`cozy-stack serve --assets=$GOPATH/src/github.com/cozy/cozy-stack/assets --couchdb-host 127.0.0.1 --couchdb-port 5984`
3. get an instance running with a preset email address (in the app's directory)
`cozy-stack instances add --dev "cozy.local:8080" --email test@test.com` 
4. run a webpack server (in the app's directory)
`yarn run watch:server`
5. go to http://localhost:8090 in your favorite browser

New fields on Settings app

---

src/styles/app.styl

Double border between the cozy-bar and the app's body
Removed the extra border from the app's body

remove extra border

---

config/webpack.base.config.js
config/webpack.copyfiles.config.js
manifest.webapp

Cozy-settings was not working with the last version of cozy-stack which requires permission management.

[feat] Make settings great again (or work again actually)

---

src/actions/index.js

This PR fixes the fetching mechanism so that they work with the latest versions of the stack.

[fix] Credentials

---

src/components/Field.jsx
src/components/ProfileView.jsx
src/components/Select.jsx

Quick refacto to make incoming form based features easier.

[refacto] Dumber inputs 📝

---

src/components/PassphraseForm.jsx

Lien direct vers la route /auth/passphrase_reset.

Set 6 new password

---

package.json
src/main.jsx
yarn.lock

⚠️ Need the next cozy-bar update (with this [PR](https://github.com/cozy/cozy-bar/pull/39)) before merging ⚠️

Change the cozy bar locale when the user change the cozy language

---

config/webpack.config.dev.js
config/webpack.config.prod.js
package.json
src/index.ejs
src/main.jsx
yarn.lock

Same as https://github.com/cozy/cozy-ui/pull/104
\+ devtools in development

chore: add piwik tracker + devtools

---

config/webpack.config.dev.js
config/webpack.config.prod.js
src/main.jsx

Tracks the user by id and by app in piwik, based on this PR : https://github.com/cozy/cozy-drive/pull/265

feat: track userid and app

---

src/components/DevicesView.jsx

https://trello.com/c/INKmUCc8/502-1-set-13-etu-je-ne-vois-pas-les-colonnes-permissions-et-derni%C3%A8res-activit%C3%A9s-dans-longlet-appareils-connect%C3%A9s

fix: Remove columns last activity and permission in devices table

---

manifest.webapp
package.json
src/actions/email.js
src/components/IntentView.jsx
src/config/claudyActions.yaml
src/containers/IntentService.jsx
src/locales/en.json
src/reducers/emailStatus.js
src/reducers/index.js
src/services.jsx
src/services/Claudy.jsx
src/services/ClaudyAction.jsx
src/services/ClaudyActionComponents/Support.jsx
src/styles/services.styl
src/styles/services/claudy.css
src/styles/services/claudySupport.css
yarn.lock

WIP:
⚠️ ⚠️ ⚠️ 
Need to merge these PRs before merging this one :
~~https://github.com/cozy/cozy-ui/pull/157~~
~~https://github.com/cozy/cozy-bar/pull/95~~
~~https://github.com/cozy/cozy-client-js/pull/194~~
⚠️ ⚠️ ⚠️ 
When released, the manifest need also to be udpated.

[WIP] Add Claudy support form

---

src/services/Claudy.jsx
src/services/ClaudyActionComponents/Support.jsx
src/styles/services/claudy.css

* Add workaround for preact issue discovered by @m4dz (https://github.com/developit/preact/issues/857)
* Minor UI improvements

Claudy improvements

---

src/styles/fields.styl

Fix cozy-bar link with underline :bug:

---

src/locales/en.json

*Please explain what this PR does here.*
If this PR relies on changes in one of our internal libraries (cozy-client-js or cozy-ui, for example), please also do the following things:
*(If not, please remove this last section.)*

Update link to desktop and mobile documentation

---

src/components/App.jsx
src/components/ProfileView.jsx
src/components/SessionsView.jsx
src/containers/Profile.jsx
src/locales/en.json

Add TOS version signed by the user to the link to TOS

feat: add tos version

---

src/actions/index.js
src/styles/storage.styl

This repo needs a huge cozy-UI update.

Update manager URL

---

package.json
src/components/DeleteAccount.jsx
src/components/export/ExportSection.jsx
src/locales/en.json
src/styles/app.styl
src/styles/devices.styl
src/styles/table.styl
src/styles/view.styl
yarn.lock

feat: update Download Data & Delete Account areas

---

src/components/2FA/Activate2FA.jsx
src/locales/en.json
src/styles/view.styl

Fix modal UI, better modal size + minor changes

Fix 2fa modal UI

---

src/index.ejs
src/services.ejs

See https://www.w3.org/TR/appmanifest/#obtaining

fix: Send cookies when fetching manifest.json

---

README.md

fix: update link to dev doc

---

src/components/ReactMarkdownWrapper.jsx
src/reducers/emailStatus.js
src/services/Support.jsx
src/styles/index.styl

Minor fixes about email sending status and markdown rendering

Markdown and email status fixes

---

manifest.webapp
src/components/App.jsx
src/services/IntentRedirect.jsx
test/__snapshots__/app.spec.js.snap

Add a way to redirect to settings pages

Handle redirect intents

---

src/actions/export.js
src/actions/passphrase.js
src/containers/Profile.jsx

Fix the exact same issue than for #172 but for other profile actions

Better handling errors from profile actions

---

src/actions/twoFactor.js
src/components/2FA/index.jsx
src/components/ProfileView.jsx
src/reducers/fields.js

Don't use a custom two_fa property anymore

Get twoFA property based on auth_mode settings

---

src/targets/browser/index.ejs
src/targets/intents/index.ejs

This reverts commit fd4f97ae2cbfcd85923cfd730bf9f18a7da1457c.

Revert "chore: :wrench: Use the favicon from the stack"

---

.travis.yml

Following https://github.com/cozy/cozy-store/commit/338551c15270ae30b2b10759f7de1f59533e60dc
and https://github.com/cozy/cozy-store/pull/551

Better Travis branches directive

---

package.json
src/targets/browser/index.jsx
yarn.lock

Used in the cozy-bar for customizations

Add cozy-client for cozy-bar

---

src/components/OffersLink.jsx
src/components/StorageView.jsx

Extract offers link in storage view

---

src/components/2FA/Passphrase2FA.jsx
src/components/2FA/TwoFactorCode.jsx
src/config/index.json
src/styles/view.styl

Email configurable will allow customization

Make email contact configurable + minor ui fixes

---

src/components/DevicesView.jsx
src/components/NoDevicesMessage.jsx

Extract NoDeviceMessage component from DevicesView

---

src/components/OffersLink.jsx
src/reducers/storageData.js

Wrong storage data causing blank screen :/

Fix storage data fetching

---

app.config.js
config/webpack.config.cozy-ui.js
src/components/App.jsx

This PR applies guidelines from https://github.com/cozy/cozy-ui/blob/master/docs/how-to-transpile.md#how-to

Use transpiled cozy-ui

---

src/targets/browser/index.jsx

Inject CozyClient in components context

---

src/reducers/fields.js
src/reducers/fields.spec.js

Reducer did not take into account the action DESACTIVATE_2FA_SUCCESS.

fix: Update checkbox after deactivating 2FA

---

CODEOWNERS

Otherwise, we have to manually add people to reviews.

chore: Add codeowners file

---

src/components/export/ExportDownload.jsx
src/components/export/ExportSection.jsx
src/styles/view.styl

* Remove unnecessary class to use utility classes
* Remove right padding for the image header

Minor modal headers improvement

---

src/components/App.jsx
src/lib/client.js
src/reducers/index.js
src/targets/browser/index.jsx

- Cozy-client use the same store as the app.
- Add a renderExtra "hook" for overrides

Same store

---

src/components/App.jsx
src/components/DeleteAccount.jsx
src/components/DeleteAccount/FormModal.jsx
src/components/DeleteAccount/FormModal.spec.js
src/targets/browser/index.jsx

We don't need to have context here for the domain any more and it wasn't working since a while.

Fix delete account

---

src/actions/index.js

*Please explain what this PR does here.*
If this PR relies on changes in one of our internal libraries (cozy-client-js or cozy-ui, for example), please also do the following things:
*(If not, please remove this last section.)*

Add enable_premium_link flag

---

src/components/ProfileView.jsx
src/locales/en.json

Some translations were missing. This fixes it

fix(ProfileView): Add missing translations

---

src/components/export/ExportSection.jsx
src/locales/en.json
src/locales/fr.json

feat: Add a button for moving your Cozy

---

package.json
src/components/ProfileView.jsx
src/components/ProfileView.spec.jsx
src/locales/fr.json
test/AppLike.jsx
test/app.spec.js
yarn.lock

If the stack does not yet put capabilities in the server variable
CozyData, we need to have the "update password" button shown.

Fix: Capabilities

---

src/actions/passphrase.js

Easier to read, coherent with the rest of the codebase.

refactor: Use async/await instead of then/catch

---

src/components/DevicesModaleConfigureView.jsx

The previous algorithm would visually select all descendants of a
`TreeView` level even when this level was itself automatically
selected because of the selection of **one** of its descendants.
The new algorithm will only select the level itself and its ancestors,
leaving the other ancestors' descendants unselected.
Other behaviors and the final exclusions are left unchanged.

Change folder selection algorithm

---

src/components/PassphraseForm.jsx
src/locales/en.json
src/locales/fr.json

Change placeholder
Button is now clickable even if there is no hint

feat: Password hint from required to optional

---

manifest.webapp
package.json

*Please explain what this PR does here.*
If this PR relies on changes in one of our internal libraries (cozy-client-js or cozy-ui, for example), please also do the following things:
*(If not, please remove this last section.)*

feat: Bump version from 1.18.0 to 1.19.0

---

src/components/App.jsx
src/containers/Permissions.jsx
src/containers/PermissionsApplication.jsx
src/containers/PermissionsApplication.spec.jsx
src/containers/__snapshots__/PermissionsApplication.spec.jsx.snap
test/__snapshots__/app.spec.js.snap

On permission page, if an app is clicked we are redirected to this app page.
With @Noemie21

feat: Display app page on click

---

src/containers/PermissionsApplication.jsx
src/containers/PermissionsApplication.spec.jsx
src/containers/__snapshots__/PermissionsApplication.spec.jsx.snap

feat(permissions): Display permissions on PermissionsApplication page

---

src/components/App.jsx
src/containers/Permission.jsx
src/containers/PermissionsApplication.jsx
src/containers/PermissionsApplication.spec.jsx
src/containers/__snapshots__/PermissionsApplication.spec.jsx.snap
test/__snapshots__/app.spec.js.snap

A new page opens when we click on a permission
with @Noemie21

feat(permissions): Redirect on permission click

---

jest.config.js
package.json
test/jestLib/resolver.js
yarn.lock

chore(jest): fix browser-resolver warning

---

src/containers/PermissionsApplication.jsx

Fixed: Now we can see permissions for both Apps and Konnectors

fix(Permissions): Permissions not loaded for konnector

---

package.json
src/containers/PermissionsApplication.jsx
src/containers/PermissionsApplication.spec.jsx
src/containers/__snapshots__/PermissionsApplication.spec.jsx.snap
src/lib/withLocales.js
yarn.lock

feat: Display permissions's translation in alphabetic order

---

package.json
src/targets/browser/index.jsx
src/targets/intents/index.jsx
yarn.lock

This reverts commit a964ea494bbea6a815b34df1a2480ad7dc3db364.

Revert "chore(react): upgrade to react-18"

---

src/containers/Permission.jsx
src/containers/__snapshots__/Permission.spec.jsx.snap

feat: Add backward arrow in Permission

---

src/containers/PermissionsApplication.jsx
src/containers/__snapshots__/PermissionsApplication.spec.jsx.snap

feat: add backward arrow in PermissionsApplication

---

src/config/permissionsIcons.json

fix(Permissions): fix banks permissions not showing

---

.gitignore

This allows us to have personal pull request templates for instance

chore: Ignore .github directory

---

src/lib/flags.js

https://github.com/cozy/cozy-settings/pull/459#discussion_r959429747

fix: Disable permissions flag

---

src/components/App.jsx
src/components/Permissions/AppList.jsx
src/components/Permissions/AppList.spec.jsx
src/components/Permissions/PermissionsTab.jsx
src/components/Permissions/PermissionsTab.spec.jsx
src/components/Permissions/__snapshots__/AppList.spec.jsx.snap
src/containers/Permission.jsx
src/containers/Permission.spec.jsx
src/containers/PermissionsApplication.jsx
src/containers/PermissionsApplication.spec.jsx
src/containers/__snapshots__/Permission.spec.jsx.snap
src/containers/__snapshots__/PermissionsApplication.spec.jsx.snap
yarn.lock

Here is the list of reviews that have been corrected: 
- [slug](https://github.com/cozy/cozy-settings/pull/438#discussion_r951064578)
- [useNavigate](https://github.com/cozy/cozy-settings/pull/438#discussion_r951065750)
- [snapshot](https://github.com/cozy/cozy-settings/pull/438#discussion_r951068812)

fix: Correction of errors in PR #438

---

src/components/Permissions/AppList.jsx
src/components/Permissions/AppList.spec.jsx
src/components/Permissions/__snapshots__/AppList.spec.jsx.snap

we use the NavigationList component in order to follow the templates

feat: Use NavigationList component

---

src/components/menu/MenuList.tsx
src/components/menu/menu.styl

Correcting padding/margin values
https://trello.com/c/J1yWZ7pS/573-%E2%9A%99%EF%B8%8F-set-menu-en-premi%C3%A8re-page-dans-lapplication-settings-4j

fix: Menu items styles

---

src/components/Permissions/AppPermissions.jsx
src/components/Permissions/AppPermissions.spec.jsx
src/components/Permissions/OpenappButton.jsx
src/components/Permissions/PermissionDetails.spec.jsx

Rename query path to delete attributes keyword

fix: rename query path to delete attributes keyword

---

src/components/Permissions/AppPermissions.jsx
src/components/Permissions/__snapshots__/AppPermissions.spec.jsx.snap

fix(Permissions): improve design using NavigationList

---

package.json
src/components/Permissions/AppList.jsx
src/components/Permissions/AppPermissions.jsx
src/components/Permissions/AppPermissions.spec.jsx
src/components/Permissions/DataList/DataList.jsx
src/components/Permissions/DataPermissions/DataPermissions.jsx
src/components/Permissions/DataPermissions/__snapshots__/DataPermissions.spec.jsx.snap
src/components/Permissions/__snapshots__/AppList.spec.jsx.snap
src/components/Permissions/__snapshots__/AppPermissions.spec.jsx.snap
yarn.lock

also standardize design in all 4 pages (AppList, AppPermissions, DataList, DataPermission)

feat: add app icon to AppPermissions

---

package.json
src/components/DevicesView.jsx
src/components/Page.tsx
src/components/Permissions/__snapshots__/PermissionsTab.spec.jsx.snap
src/components/SessionsView.jsx
src/components/SessionsView/SessionDialog.tsx
src/components/SessionsViewRow.jsx
src/locales/en.json
src/locales/fr.json
src/styles/table.styl
yarn.lock

https://github.com/cozy/cozy-settings/pull/487 without the refactor asked by https://github.com/cozy/cozy-settings/pull/487#discussion_r982270056 .
In case, the PR needs to pass, and if I don't have the time to finish it... This PR has been tested, and should work.

 feat(mobile): Add mobile view improvement on DeviceView and SessionView page

---

manifest.webapp
src/components/Permissions/AppPermissions.jsx
src/components/Permissions/__snapshots__/AppPermissions.spec.jsx.snap
src/locales/en.json
src/locales/fr.json

+ add title for 'limited right access' section

feat: Add 'Latest data releases' section

---

src/components/dialogs/PinCodeDialog.tsx
src/components/pages/LockScreen.tsx
src/locales/fr.json

fix: improve lockscreen consistency

---

manifest.webapp
src/components/Permissions/AppPermissions.jsx
src/components/Permissions/AppPermissions.spec.jsx
src/components/Permissions/__snapshots__/AppPermissions.spec.jsx.snap
src/locales/en.json
src/locales/fr.json

feat: Display modal with released data

---

package.json
src/components/Permissions/helpers/permissionsHelper.js
src/lib/withAllLocales.spec.js
yarn.lock

Added doctypes translation in cozy-client

feat: Upgrade cozy-client to get remote-doctypes locales

---

src/components/Permissions/AccessRightsSection.jsx
src/components/Permissions/LatestOutgoingDataHistory.jsx
src/components/Permissions/helpers/permissionsHelper.js

This function is not useful. Improved code by removing it and checking with the index.

fix: Remove is not last item function

---

src/components/Permissions/DataPermissions/DataPermissions.jsx
src/components/Permissions/DataPermissions/DataPermissions.spec.jsx
src/components/Permissions/DataPermissions/__snapshots__/DataPermissions.spec.jsx.snap

feat: filter apps and konnectors in DataPermissions

---

src/components/Permissions/AppList.jsx
src/components/Permissions/DataList/DataList.jsx
src/components/Permissions/DataList/DataList.spec.jsx
src/components/Permissions/PermissionsTab.jsx
src/components/Permissions/__snapshots__/AppList.spec.jsx.snap
src/components/Permissions/__snapshots__/PermissionsTab.spec.jsx.snap

Change title to "Permissions"
Desktop: Align title with Tabs
Mobile: Center Title and Tabs

feat: Improve DataList and AppList headers

---

src/components/Permissions/AppPermissions/AppPermissions.jsx
src/components/Permissions/AppPermissions/__snapshots__/AppPermissions.spec.jsx.snap

Mobile: Center verticaly, remove previous arrow
Desktop: reorganize

feat: Improve AppPermissions Header

---

src/components/Sidebar.tsx

Added a conditional to the item render so it only appears on the web

feat: offersLink is not available in native app

---

manifest.webapp
package.json

feat: bump version from 1.19.0 to 1.20.0

---

src/lib/makeDiskInfos.spec.ts
src/lib/makeDiskInfos.ts

It was wrongly displayed in gibibyte

fix: display storage data in gigabyte

---

src/components/Permissions/AccessRightsDetailsSection.jsx
src/components/Permissions/AccessRightsSection.jsx
src/components/Permissions/AppPermissions/AppPermissions.jsx
src/components/Permissions/LatestOutgoingDataHistory.jsx
src/locales/en.json
src/locales/fr.json

also change color of the divider

feat: Add modal for AppPermissions elements

---

package.json
src/components/DeleteAccount.jsx
src/components/PassphraseForm.jsx
src/hooks/useCanAuthWith.spec.js
src/hooks/useCanAuthWith.ts
yarn.lock

```
* Skip password confirmation if can auth with OIDC when delete account
```

Feat: Skip password confirmation if can auth with OIDC when delete account

---

package.json
src/locales/en.json
src/locales/fr.json
src/services/ClaudyActionComponents/Support.jsx
src/services/Support.jsx
src/services/Support.spec.jsx
yarn.lock

** Related PRs: ** 
- https://github.com/cozy/cozy-bar/pull/814
- https://github.com/cozy/cozy-bar/pull/815

Feat: Add consent checkbox on support message

---

.tx/config
CONTRIBUTING.md
README.md
src/locales/nl_NL.json

```
* Migrate transifex config from v2 to v3
```

chore: Migrate transifex config from v2 to v3

---

src/components/App.jsx
src/components/Sidebar.tsx
src/components/Support/Support.jsx
src/components/Support/Support.spec.jsx
src/components/Support/support.styl
src/constants/routes.ts
src/locales/en.json
src/locales/fr.json

In cozy-bar, we redirect to the support page rather than opening a modal like that the contact page is available directly from cozy-settings in the menu
```
* Add support page to contact us
```

feat: Add support page

---

src/config/permissionsIcons.json

sinister doesn't exist. Sinister yes.
https://docs.cozy.io/cozy-ui/react/#!/Icon

fix: Case sensitive

---

src/components/2FA/index.jsx
src/components/ProfileView.jsx

The instance information was out of date after an update of the 2FA which caused problems in other actions such as updating the password

fix: Update instance after 2FA mutation

---

src/components/2FA/index.jsx
src/components/PasswordSection.jsx
src/components/PasswordSection.spec.jsx
src/components/ProfileView.jsx
src/hooks/useOffersLink.ts
src/reducers/fields.js
src/reducers/fields.spec.js

This patch is the improvement around after the review of https://github.com/cozy/cozy-settings/pull/586. Unfortunately, the PR was automatically merged before the new changes were pushed. Therefore I revert the commit from the previous PR before reapply new changes.

fix: Update instance data after 2FA activation

---

src/locales/fr.json

With this PR, I will also be able to see if the Transifex integration is working as intended

fix(Subscription): Missing ":" in french wording

---

src/components/Email/ChangeEmail.jsx
src/components/Email/EmailModal.jsx

```
* Allow to skip email confirmation in some context with flag settings.skip_email_confirmation
```
**Related PRs:**
- https://github.com/cozy/cozy-client/pull/1377

feat: Allow to skip email confirmation in some context

---

manifest.webapp
package.json

```
* Bump version to 1.30.0
```

feat: Bump version to 1.30.0

---

src/locales/en.json
src/locales/fr.json

```
* Rename page subscription
```

feat: Rename page subscription

---

manifest.webapp
package.json

```
* Bump version to 1.31.0
```

feat: Bump version to 1.31.0

---

src/components/Subscription/Subscription.jsx
src/components/Subscription/helper.js
src/locales/en.json
src/locales/fr.json

```
* Show max for CoachCO2 if defined in Subscription page
```

[VO-167] feat(Subscription): Show max for CoachCO2 if defined

---

manifest.webapp
package.json

```
* Bump version to 1.32.0
```

feat: Bump version to 1.32.0

---

package.json
src/components/App.jsx
src/targets/browser/index.jsx
yarn.lock

```
* Add sentry to monitor crash event
```

[VO-327] feat: Add sentry

---

CODEOWNERS
src/components/menu/MenuItemSwitch.tsx
src/cozy-ui.d.ts

```
* Disable ellipsis on the LockScreen
```

[VO-392] fix(LockScreen): Disable ellipsis

---

src/components/App.jsx
src/components/Permissions/AppPermissions/AccessRightsSection.jsx
src/components/Permissions/AppPermissions/AppPermissions.jsx
src/components/Permissions/AppPermissions/LatestOutgoingDataHistory.jsx
src/components/Permissions/DataList/DataList.jsx
src/components/Permissions/DataPermissions/DataPermissions.jsx
src/lib/flags.js

```
* Remove ellipsis on items into Permissions page
```

[VO-392] fix: Remove ellipsis on items into Permissions page

---

package.json
yarn.lock

```
* Update cozy-bar from 11.0.0 to 12.0.0
```

[VO-421] feat: Update cozy-bar from 11.0.0 to 12.0.0

---

.travis.yml
package.json
release.config.js
yarn.lock

This commit add semantic-release to help us publish new version on every branch merge into master.
We add a commit with the modification of the version in the `package.json` and the `manifest.webapp`. This commit has the tag of the new version associated with it. After we still use cozy-app-publish to push the build to the registry and downcloud.
```
* Make continuous deployement
```

[VO-591] chore: Make continuous deployement

---

package.json
release.config.js
yarn.lock

```
* Avoid publishing messages after a release on Github
```

chore: Avoid publishing messages after a release on Github

---

.travis.yml
src/services/ClaudyAction.jsx

This PR also test the new continuous deployement

chore: Optimize Travis CI & small fix

---

package.json
release.config.js
yarn.lock

```
* Update cozy-bar from 12.0.0 to 12.2.1
```

feat: Update cozy-bar from 12.0.0 to 12.2.1

---

package.json
release.config.js
yarn.lock

```
* Update cozy-bar from 12.2.1 to 12.2.3
```

[VO-591] feat: Update cozy-bar from 12.2.1 to 12.2.3

---

src/components/BlockingSubscriptionModal/BlockingSubscriptionModal.jsx
src/components/BlockingSubscriptionModal/index.js
src/components/DeleteAccount/DeleteAccount.jsx
src/components/export/MoveButton.jsx
src/lib/flags.js
src/locales/en.json
src/locales/fr.json

This feature can be activated with `settings.specify-blocking-subscription-vendor-dev`

[VO-531] feat: Specify the blocking subscription vendor

---

package.json
src/components/Devices/DevicesModaleConfigureView.jsx
src/components/Devices/DevicesModaleRevokeView.jsx
src/components/Devices/DevicesView.jsx
src/components/Devices/__snapshots__/DevicesModaleConfigureView.spec.jsx.snap
src/components/SessionsView.jsx
src/components/SessionsViewRow.jsx
src/components/dialogs/BiometryDeniedDialog.tsx
src/components/dialogs/PinCodeDialog.tsx
src/cozy-ui.d.ts
src/services/ClaudyActionComponents/Support.jsx
src/services/Support.jsx
src/styles/fields.styl
src/styles/index.styl
src/styles/services/claudy.css
src/styles/services/support.css
src/styles/storage.styl
yarn.lock

```
* Add better support for dark mode
```

Add better support for dark mode

---

src/locales/en.json
src/locales/fr.json

```
* Change wording to select display mode
```

feat: Change wording to select display mode

---

src/components/Appearance/AppearanceView.jsx

```
* Support custom color scheme in flagship app
*
*
```
Linked PR : https://github.com/cozy/cozy-flagship-app/pull/1222

Support custom color scheme in flagship app

---

package.json
yarn.lock

```
* Update cozy-ui from 110.1.0 to 110.8.1
```

[VO-902] feat: Update cozy-ui from 110.1.0 to 110.8.1

---

package.json
yarn.lock

```
* Update cozy-bar from 15.0.0 to 16.0.0
* Update cozy-flags from 3.2.2 to 4.6.1
```

[VO-1186] feat: Update cozy-bar from 15.0.0 to 16.0.0

---

src/components/Devices/helpers.js
src/components/Devices/helpers.spec.js

fix: Blank page when no software_version
